version: "3"
services:
    web:
      image: optl-monitor:latest
      ports:
          - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coupon
        SPRING_DATASOURCE_USERNAME: myuser
        SPRING_DATASOURCE_PASSWORD: secret
        OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
        OTEL_EXPORTER_OTLP_PROTOCOL: grpc
        OTEL_METRIC_EXPORT_INTERVAL: 500
        OTEL_BSP_SCHEDULE_DELAY: 500
        OTEL_SERVICE_NAME: "order-service"
        OTEL_RESOURCE_ATTRIBUTES: "service.name=order-service,env=dev,compose_service=app-order"
        OTEL_INSTRUMENTATION_MICROMETER_ENABLED: true
    external:
      image: optl-monitor:latest
      ports:
        - "8081:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coupon
        SPRING_DATASOURCE_USERNAME: myuser
        SPRING_DATASOURCE_PASSWORD: secret
        OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
        OTEL_EXPORTER_OTLP_PROTOCOL: grpc
        OTEL_METRIC_EXPORT_INTERVAL: 500
        OTEL_BSP_SCHEDULE_DELAY: 500
        OTEL_SERVICE_NAME: "external-service"
        OTEL_RESOURCE_ATTRIBUTES: "service.name=external-service,env=dev,compose_service=app-order"
        OTEL_INSTRUMENTATION_MICROMETER_ENABLED: true
    alloy:
      image: grafana/alloy:latest
      container_name: alloy
      volumes:
        - ./alloy/config.alloy:/etc/alloy/config.alloy
      ports:
        - "12345:12345"
        - "4317"
        - "4318"
      command: >
        run
        --server.http.listen-addr=0.0.0.0:12345
        --storage.path=/var/lib/alloy/data
        /etc/alloy/config.alloy
    loki:
      image: grafana/loki:3.0.0
      command: [ "--pattern-ingester.enabled=true", "-config.file=/etc/loki/loki.yaml" ]
      ports:
        - "3100:3100"
      volumes:
        - "./loki/loki.yaml:/etc/loki/loki.yaml"
#    prometheus:
#      container_name: prometheus
#      image: prom/prometheus
#      volumes:
#        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      command:
#        - --web.enable-remote-write-receiver
#        - --enable-feature=otlp-write-receiver
#        - --enable-feature=exemplar-storage
#        - --enable-feature=native-histograms
#        - --config.file=/etc/prometheus/prometheus.yml
#      restart: always
#      ports:
#        - '9090:9090'
    tempo:
      container_name: tempo
      image: grafana/tempo:latest
      command: [ "-config.file=/etc/tempo.yml" ]
      volumes:
        - ./tempo/tempo.yml:/etc/tempo.yml
      restart: always
      ports:
        - "4317"  # otlp grpc
        - "3200"  # tempo as grafana datasource
    grafana:
      container_name: grafana
      image: grafana/grafana
      restart: always
      ports:
        - "3000:3000"
    postgres:
      image: 'postgres:latest'
      environment:
        - 'POSTGRES_DB=coupon'
        - 'POSTGRES_USER=myuser'
        - 'POSTGRES_PASSWORD=secret'
      ports:
        - '5432:5432'
    mimir:
      image: grafana/mimir:latest
      command:
        - -config.file=/etc/mimir.yaml
      ports:
        - "9009:9009"
      volumes:
        - ./mimir/mimir.yaml:/etc/mimir.yaml
        - ./mimir/data:/data