
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
      tags:
        application: ${OTEL_SERVICE_NAME}
      enable:
        tomcat: true
        jvm: false
        process: false
        hikaricp: false
        system: false
        jdbc: false
        http: false
        logback: true
  distribution:
    percentiles-histogram:
      http:
        server:
          requests: 'true'
    minimum-expected-value:
      http.server.requests: 5ms
    maximum-expected-value:
      http.server.requests: 1000ms

  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
logging:
  pattern:
    level: "%5p [${OTEL_SERVICE_NAME:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.example.optlmonitor: debug
spring:
  sql:
    init:
      mode: always
  mvc:
    problemdetails:
      enabled: true