
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
      tags:
        application: ${OTEL_SERVICE_NAME}
      enable:
        tomcat: true
        jvm: false
        process: false
        hikaricp: false
        system: false
        jdbc: false
        http: true
        logback: true
      distribution:
        percentiles-histogram:
          http:
            server:
              requests: 'true'
        maximum-expected-value:
          http.server.requests: 1000ms
        minimum-expected-value:
            http.server.requests: 5ms
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
logging:
  pattern:
    # https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/logger-mdc-instrumentation.md
    level: "[${OTEL_SERVICE_NAME:},trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags}] %5p"
  level:
    com.example.optlmonitor: debug
spring:
  sql:
    init:
      mode: always
  mvc:
    problemdetails:
      enabled: true